config/routes.rb
Rails.application.routes.draw do

  resources :products

  get 'products/search', to: 'products#search'
    
  resources :tasks do
    get :autocomplete_product_name, :on => :collection
  end

  root 'home#index' 

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :tasks_products
	has_many :tasks, :through => :tasks_products
	#has_and_belongs_to_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :tasks_products
	has_many :products, :through => :tasks_products
	accepts_nested_attributes_for :tasks_products, reject_if: :all_blank, allow_destroy: true

	def self.status
		["Na Fila", "Em produção", "Pronto para Entrega", "Finalizado"]
	end
end

app/models/tasks_product.rb
class TasksProduct < ActiveRecord::Base
  belongs_to :task
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    search = params[:search].nil? ? '' : params[:search].downcase
    @products = Product.where("LOWER(name) LIKE ?", "%#{search}%")
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:cost_value, :sale_value, :name, :quantity_in_stock)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  autocomplete :product, :name

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    search = params[:search].nil? ? '' : params[:search].downcase
    @tasks = Task.where("LOWER(client_name) LIKE ?", "%#{search}%")
    respond_to do |format|
      format.js {}
      format.html {}
    end

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.status = Task.status.first
    # task_params[:tasks_products_attributes].each do |p|
    #   puts p[:product_id]
    # end

    respond_to do |format|
      if @task.save
        @task.tasks_products.each do |t|
          product = Product.find_by_id(t.product)
          product.update(quantity_in_stock: product.quantity_in_stock - t.quantity)
        end
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:client_name, :value, :discount, :final_value, :status, tasks_products_attributes:[:id, :product_id, :task_id, :file_name, :quantity, :obs])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Home" %></h1>
</div>

<dl class="dl-horizontal">
	<%= link_to t('.new', :default => t("Vendas")),
            tasks_path,
            :class => 'btn btn-primary' %>
<br>
<br>
    <%= link_to t('.new', :default => t("Produtos")),
            products_path,
            :class => 'btn btn-primary' %>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Difranco</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/">Home</a></li>
				<li><%= link_to t('.new', :default => t("Produtos")),
				products_path%></li>
				<li><%= link_to t('.new', :default => t("Vendas")),
				tasks_path%></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
			</ul>
		</div>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cost_value, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cost_value, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cost_value) %>
  </div>
  <div class="form-group">
    <%= f.label :sale_value, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sale_value, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sale_value) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :quantity_in_stock, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :quantity_in_stock, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quantity_in_stock) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/_products_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Valor de Custo</th>
      <th>Valor de Venda</th>
      <th>Nome</th>
      <th>Quantidade em Estoque</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.name, product_path(product) %></td>
      <td><%= product.cost_value %></td>
      <td><%= product.sale_value %></td>
      <td><%= product.quantity_in_stock %></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_product_path(product), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        product_path(product),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag products_path, :method => 'get', remote: true do %>
<p>
  <div class="col-lg-10">
    <%= text_field_tag :search, params[:search], class: 'form-control' %>
  </div>
  <div class="col-lg-2">
    <%= submit_tag "Procurar", :name => nil, class: 'btn btn-primary' %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
new_product_path,
:class => 'btn btn-primary' %>
  </div>
</p>
<% end %>
<div id="products_table">
  <%= render partial: 'products_table', locals: {products: @products}%>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:cost_value) %>:</strong></dt>
  <dd><%= @product.cost_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sale_value) %>:</strong></dt>
  <dd><%= @product.sale_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity_in_stock) %>:</strong></dt>
  <dd><%= @product.quantity_in_stock %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => "form-horizontal task" } do |f| %>
<% if @task.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="form-group">
  <%= f.label :client_name, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :client_name, :class => 'form-control' %>
  </div>
  <%=f.error_span(:client_name) %>
</div>
<h5 class="col-lg-12 text-center"> Produtos </h5>
<div class="form-group" id="tasks_products_container">
  <%=f.fields_for :tasks_products do |task_product|%>
    <%= render :partial => 'tasks_product_fields', f: task_product, 'data-association-insertion-method' => "append"%>
  <%end%>
  <%= link_to_add_association 'Adicionar Produto', f, :tasks_products, class: 'col-lg-12 text-center'%>
</div>

<div class="form-group">
  <%= f.label :value, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :value, :class => 'form-control' %>
  </div>
  <%=f.error_span(:value) %>
</div>
<div class="form-group">
  <%= f.label :discount, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :discount, :class => 'form-control' %>
  </div>
  <%=f.error_span(:discount) %>
</div>
<div class="form-group">
  <%= f.label :final_value, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :final_value, :class => 'form-control' %>
  </div>
  <%=f.error_span(:final_value) %>
</div>
<% if action_name.eql? "edit"%>
<div class="form-group">
  <%= f.label :status, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.select :status, Task.status, {:selected => Task.status.grep(@task.status)}, :class => "btn btn-default dropdown-toggle" %>
  </div>
  <%=f.error_span(:status) %>
</div>
<%end%>
<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    tasks_path, :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

app/views/tasks/_tasks_product_fields.html.erb
<li class="nested-fields">
	<%= f.label :product_id, "Nome do Produto", :class => 'control-label col-lg-4'%>
	<div class="col-lg-6">
		<%= autocomplete_field_tag "product_name", "", autocomplete_product_name_tasks_path, class: 'form-control', :id_element => 'meuid'%>
		<%= f.hidden_field(:product_id, value: "0")%>
	</div>
	<%= f.label :file_name, "Nome Arquivo:", :class => 'control-label col-lg-4'%>
	<div class="col-lg-6">
		<%= f.text_field :file_name, class: 'form-control'%>
	</div>
	<%= f.label :quantity, "Quantidade:", :class => 'control-label col-lg-4'%>
	<div class="col-lg-6">
		<%= f.number_field :quantity, class: 'form-control' %>
	</div>
	<%= f.label :obs, "Observação:", :class => 'control-label col-lg-4'%>
	<div class="col-lg-6">
		<%= f.text_area :obs, class: 'form-control' %>
	</div>
	<div class="col-lg-12 text-center">
		<%= link_to_remove_association "Remover Produto", f%>
	</div>
</li>

app/views/tasks/_tasks_products.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Nome do Arquivo</th>
      <th>Observaçao</th>
    </tr>
  </thead>
  <tbody>
    <% @task.tasks_products.each do |tp| %>
      <tr>
        <td><%=tp.product.name%></td>
        <td><%= tp.quantity %></td>
        <td><%= tp.file_name %></td>
        <td><%= tp.obs %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/_tasks_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome do Cliente</th>
      <th>Valor</th>
      <th>Desconto</th>
      <th>Valor Final</th>
      <th>Status</th>
      <th>Criado em</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.client_name, task_path(task) %></td>
      <td><%= task.value %></td>
      <td><%= task.discount %></td>
      <td><%= task.final_value %></td>
      <td><%= task.status %></td>
      <td><%=l task.created_at %></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_task_path(task), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.show', :default => t("helpers.links.show")),
        task_path(task), :class => 'btn btn-success btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        task_path(task),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Vendas" %></h1>
</div>
<%= form_tag tasks_path, :method => 'get', remote: true do %>
<p>
  <div class="col-lg-9">
    <%= text_field_tag :search, params[:search], class: 'form-control' %>
  </div>
  <div class="col-lg-3">
    <%= submit_tag "Procurar", :name => nil, class: 'btn btn-primary' %> 
    <%= link_to t('.new', :default => t("Nova venda")),
    new_task_path,
    :class => 'btn btn-primary' %>
  </div>
</p>
<% end %>

<div id="tasks_table">
  <%= render partial: 'tasks_table', locals: {tasks: @tasks}%>
</div>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:client_name) %>:</strong></dt>
  <dd><%= @task.client_name %></dd>


  <dt><strong><%= "Produtos" %>:</strong></dt>
  <dd><%= render partial: 'tasks_products', locals: {task: @task}%></dd>


  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @task.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @task.discount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:final_value) %>:</strong></dt>
  <dd><%= @task.final_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @task.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>